version: "3.9"

services:
  procurement-frontend:
    build:
      context: .
      args:
        NEXT_PUBLIC_BACKEND_API_URL: ${NEXT_PUBLIC_BACKEND_API_URL}
        NEXT_PUBLIC_FRONTEND_URL: ${NEXT_PUBLIC_FRONTEND_URL}
    env_file:
      - .env
    networks:
      - frontend

  procurement-nginx:
    build: ./nginx
    ports:
      - "3000:80"
    depends_on:
      - procurement-frontend
    networks:
      - frontend

networks:
  frontend:
    driver: bridge
